In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("loan_approval_data.csv")

In [4]:
df.sample(10)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
530,NaN,8042.0,9989.0,Salaried,37.0,Married,NaN,576.0,4.0,0.44,19541.0,19043.0,28066.0,60.0,Car,Urban,Graduate,Female,NaN,No
436,437.0,15923.0,9768.0,Contract,25.0,Single,1.0,702.0,0.0,0.40,5137.0,10564.0,34092.0,84.0,Business,Urban,NaN,Male,Government,No
977,978.0,8150.0,5693.0,Self-employed,24.0,Married,2.0,562.0,2.0,0.31,2329.0,12974.0,6004.0,36.0,Education,Urban,Graduate,Female,Unemployed,No
925,926.0,6243.0,1048.0,Salaried,38.0,Married,1.0,744.0,2.0,0.23,4377.0,32161.0,34362.0,24.0,Car,Rural,Not Graduate,Male,Business,No
827,828.0,7373.0,4255.0,Contract,30.0,Married,0.0,719.0,1.0,0.32,13406.0,15021.0,24813.0,84.0,Business,Urban,Graduate,Female,Government,Yes
773,774.0,5490.0,5699.0,Unemployed,31.0,Single,1.0,620.0,4.0,0.56,12894.0,41684.0,24940.0,12.0,Home,Urban,Not Graduate,Female,Government,No
664,665.0,10150.0,6924.0,Salaried,57.0,Single,1.0,669.0,1.0,0.39,9884.0,17718.0,11528.0,12.0,Education,Rural,Graduate,Female,Private,Yes
602,603.0,8949.0,6262.0,Contract,52.0,Married,0.0,766.0,4.0,0.35,7145.0,21740.0,25474.0,24.0,Education,Rural,Graduate,Female,Private,Yes
71,72.0,18448.0,1762.0,Contract,42.0,Married,2.0,753.0,3.0,0.11,12128.0,23457.0,27179.0,24.0,Business,Semiurban,Graduate,Male,Private,Yes
711,712.0,17679.0,9135.0,Salaried,52.0,Married,1.0,790.0,2.0,0.54,18899.0,48127.0,8140.0,NaN,Education,Rural,Not Graduate,Female,Government,No

In [13]:
df.info()
df.isnull().sum()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    object
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    object
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    object
 15  Property_Area       950 non-null    object
 16  Education_Level     950 non-null    object
 17  Gender              950 non-null    object
 18  Employer_Category   950 non-null    object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

# Handle Missing Values

In [18]:
categorical_cols = df.select_dtypes(include = ["object"]).columns
numerical_cols = df.select_dtypes(include = ["number"]).columns
#number include all numerical values like float and int and if we want any specific data type we can write only the particular data type.

In [24]:
#SimpleImputer to fill categorical and numerical val with particular val like mean, mode, median

from sklearn.impute import SimpleImputer
num_imp = SimpleImputer(strategy="mean")
df[numerical_cols] = num_imp.fit_transform(df[numerical_cols])

cat_imp = SimpleImputer(strategy = "most_frequent")
df[categorical_cols] = cat_imp.fit_transform(df[categorical_cols])

Applicant_ID          0
Applicant_Income      0
Coapplicant_Income    0
Employment_Status     0
Age                   0
Marital_Status        0
Dependents            0
Credit_Score          0
Existing_Loans        0
DTI_Ratio             0
Savings               0
Collateral_Value      0
Loan_Amount           0
Loan_Term             0
Loan_Purpose          0
Property_Area         0
Education_Level       0
Gender                0
Employer_Category     0
Loan_Approved         0
dtype: int64